AWSTemplateFormatVersion: "2010-09-09"
Description: "Please Take My Dog Roles And Policies"

Parameters:
  StackName:
    Type: String
    Default: ptmd
    Description: The name of the stack consuming the roles declared within this stack.

Resources:
  ApiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com

  CloudformationPtmd:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: CloudformationPtmd
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudformation:*
            Resource:
            - !Sub arn:aws:cloudformation:*:*:stack/${StackName}/*
            - arn:aws:cloudformation:eu-west-1:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action:
            - lambda:*
            Resource: "*"
          - Effect: Allow
            Action:
            - apigateway:*
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - sns:*
            Resource:
            - !Sub arn:aws:sns:*:*:${StackName}-*
          - Effect: Allow
            Action:
            - cloudwatch:DeleteAlarms
            - cloudwatch:PutMetricAlarm
            - cloudwatch:DescribeAlarms
            Resource: "*"
          - Effect: Allow
            Action:
            - events:DeleteRule
            - events:DescribeRule
            - events:ListRules
            - events:ListTargetsByRule
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            Resource: "*"
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub arn:aws:iam::*:role/${AWS::StackName}-*
          - Effect: Allow
            Action: logs:*
            Resource: "*"
          - Effect: Allow
            Action:
              - ssm:AddTagsToResource
              - ssm:DeleteParameter
              - ssm:PutParameter
              - ssm:RemoveTagsFromResource
            Resource: arn:aws:ssm:*:*:parameter/*
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com

Outputs:
  ApiFunctionRoleArn:
    Value: !GetAtt ApiFunctionRole.Arn
    Description: The ApiFunctionRole Arn
    Export:
      Name: !Sub "${AWS::StackName}-ApiFunctionRoleArn"
