version: 2.1

jobs:
  test-and-package:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2.204
    steps:
      - checkout
      - run:
          name: Test and package
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install -g Cake.Tool 
            dotnet cake --target=Package
      - persist_to_workspace:
            root: .
            paths:
              - template.yaml
              - publish
  deploy:
    docker:
     - image: circleci/python:3-node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run: 
          name: Create change set
          command: |
            CHANGESET_NAME=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            S3_PREFIX=ptmd-website/$CHANGESET_NAME
            aws cloudformation package --template-file template.yaml \
               --s3-bucket $CF_DEPLOYMENT_S3_BUCKET \
               --s3-prefix $S3_PREFIX \
               --output-template-file template-packaged.yaml
            aws s3 cp template-packaged.yaml s3://$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/
            aws cloudformation create-change-set \
              --template-url https://s3-eu-west-1.amazonaws.com/$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/template-packaged.yaml \
              --stack-name ptmd \
              --change-set-name $CHANGESET_NAME \
              --description "Created by CircleCI $CIRCLE_BUILD_URL"
              
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test-and-package
      - deploy:
          requires:
            - test-and-package
